package com.petnexus.backend.entity;

import com.petnexus.backend.enums.UserRole;
import com.petnexus.backend.enums.UserStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * User entity — persisted to the centralized PetNexus SQL Server database.
 * Table: [PetNexus].[dbo].[users]
 *
 * This is the single user table shared by all six operational roles and the
 * System Administrator. Do NOT create separate user tables per role.
 *
 * Password is stored as a BCrypt hash in passwordHash.
 * The passwordHash field is NEVER included in API responses (see UserResponse DTO).
 */
@Entity
@Table(
    name = "users",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_users_user_id", columnNames = "userId"),
        @UniqueConstraint(name = "uk_users_email", columnNames = "email")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /** Internal auto-generated primary key. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Business-facing user identifier in USR-xxx format.
     * Unique across the system. Generated by UserService on registration.
     */
    @Column(nullable = false, length = 20)
    private String userId;

    // -----------------------------------------------------------------------
    // Core Authentication Fields
    // -----------------------------------------------------------------------

    @Column(nullable = false, length = 255)
    private String email;

    /**
     * BCrypt hashed password. NEVER stored as plain text.
     * NEVER returned in any API response.
     */
    @Column(nullable = false, length = 255)
    private String passwordHash;

    // -----------------------------------------------------------------------
    // Profile Fields
    // -----------------------------------------------------------------------

    @Column(nullable = false, length = 150)
    private String fullName;

    @Column(length = 30)
    private String phone;

    @Column(length = 300)
    private String address;

    @Column(length = 200)
    private String emergencyContact;

    @Column(length = 500)
    private String avatarUrl;

    // -----------------------------------------------------------------------
    // Role & Status
    // Stored as strings so the enum label matches the frontend values exactly.
    // -----------------------------------------------------------------------

    /**
     * The user's operational role or Admin.
     * Registration endpoint blocks self-assignment of Admin role.
     * Approval workflow transitions UserStatus only — never UserRole.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private UserRole role;

    /**
     * Account lifecycle status.
     * Follows: PendingApproval → Active/Rejected
     * Suspended is a separate administrative action.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 40)
    @Builder.Default
    private UserStatus status = UserStatus.PendingApproval;

    // -----------------------------------------------------------------------
    // Role-Specific Professional Fields
    // All nullable — only populated for the relevant role.
    // -----------------------------------------------------------------------

    /** Veterinarian: SLVC license number */
    @Column(length = 50)
    private String licenseNumber;

    /** Veterinarian: area of specialization */
    @Column(length = 150)
    private String specialization;

    /** ClinicStaff: staff ID badge */
    @Column(length = 30)
    private String staffId;

    /** ClinicManager: manager authorization code */
    @Column(length = 30)
    private String managerCode;

    /** RescueOfficer: rescue badge number */
    @Column(length = 30)
    private String badgeNumber;

    /** PetCareProvider: service specialty description */
    @Column(length = 150)
    private String serviceSpecialty;

    // -----------------------------------------------------------------------
    // Approval / Suspension Reasons
    // -----------------------------------------------------------------------

    @Column(length = 500)
    private String rejectionReason;

    @Column(length = 500)
    private String suspensionReason;

    // -----------------------------------------------------------------------
    // Token Fields (ephemeral — cleared after use)
    // -----------------------------------------------------------------------

    /** UUID token for password reset link. Cleared after reset. */
    @Column(length = 100)
    private String passwordResetToken;

    /** UUID token for monitoring approval status and securely exchanging for JWT upon activation. */
    @Column(length = 100)
    private String approvalToken;

    // -----------------------------------------------------------------------
    // Timestamps
    // -----------------------------------------------------------------------

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
