IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USER' AND COLUMN_NAME = 'user_id' AND DATA_TYPE = 'int')
BEGIN
    WHILE(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'))
    BEGIN
        DECLARE @sql_fk NVARCHAR(MAX);
        SELECT TOP 1 @sql_fk = 'ALTER TABLE [' + TABLE_SCHEMA + '].[' + TABLE_NAME + '] DROP CONSTRAINT [' + CONSTRAINT_NAME + ']' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'FOREIGN KEY';
        EXEC(@sql_fk);
    END;
    WHILE(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME != 'flyway_schema_history' AND TABLE_TYPE = 'BASE TABLE'))
    BEGIN
        DECLARE @sql_t NVARCHAR(MAX);
        SELECT TOP 1 @sql_t = 'DROP TABLE [' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME != 'flyway_schema_history' AND TABLE_TYPE = 'BASE TABLE';
        EXEC(@sql_t);
    END;
END;
^^^
